version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gymdb
      MYSQL_USER: gym
      MYSQL_PASSWORD: gympass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: xideral4321
      MONGO_INITDB_DATABASE: gym_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mysql_data:
  mongo_data:
