# =================================================
# SERVER CONFIG
# =================================================
server:
  port: 8080

# =================================================
# MYSQL CONFIG
# =================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gymdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: gym
    password: gympass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # Hibernate crea/actualiza tus entidades
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.time_zone: UTC

  batch:
    initialize-schema: always        # Spring Batch crea las tablas automáticamente
    jdbc:
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
    job:
      enabled: true

  # =================================================
  # MONGODB CONFIG
  # =================================================
  data:
    mongodb:
      uri: mongodb://admin:xideral234@localhost:27017/gym_mongo?authSource=admin


# =================================================
# LOGGING
# =================================================
logging:
  level:
    org.springframework: INFO
    com.example.gym: DEBUG

# =================================================
# OPENAPI / SWAGGER
# =================================================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
